/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package index;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFrame;
import koneksi.koneksi;

/**
 *
 * @author User
 */
public class admin extends javax.swing.JFrame {
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;

    /**
     * Creates new form admin
     */
    public admin() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        kosong();
        aktif();
        datatable();
        autonumber();
    }
    protected void aktif(){
        txtnama.requestFocus();
        }
    
    protected void kosong(){
          txtid.setText("");
          txtnama.setText("");
          txttelp.setText("");
          txtemail.setText("");
          txtpw.setText("");
          buttonGroup1.clearSelection();
    }
    
    protected void datatable(){
        Object[] Baris ={"id_admin","nama","jenis_kelamin","no_telepon","email","password"};//nama kolom table
            tabmode = new DefaultTableModel(null, Baris);
            //tbl_penduduk.setModel(tabmode);
            String cariitem = txtcari.getText();
            try {
                String sql = "SELECT * FROM admin where id_admin like '%"+ cariitem +"%' or nama like '%"+ cariitem+"%' order by id_admin asc";
                Statement stat = conn.createStatement();
                ResultSet hasil = stat.executeQuery(sql);
                while (hasil.next()){
                    tabmode.addRow(new Object[]{
                        hasil.getString(1),
                        hasil.getString(2),
                        hasil.getString(3),
                        hasil.getString(4),
                        hasil.getString(5),
                        hasil.getString(6)
                    });
                }
                tbladmin.setModel(tabmode);
        } catch (SQLException e){
            JOptionPane.showMessageDialog(null, "data gagal dipanggil"+e);
        }
    }
      protected void autonumber(){
        try{
            String sql = "SELECT id_admin FROM nota ORDER BY id_admin asc";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            txtid.setText("ADM0001");
            while (rs.next()){
                String idadmin = rs.getString("id_admin").substring(2);
                int AN = Integer.parseInt(idadmin) + 1;
                String Nol = "";
                
                if(AN<10)
                {Nol = "000";}
                else if(AN<100)
                {Nol = "00";}
                else if (AN<1000)
                {Nol = "0";}
                else if(AN<10000)
                {Nol = "";}
                
                txtid.setText("ADM" + Nol + AN);
            }            
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Auto Number Gagal" +e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbladmin = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtcari = new javax.swing.JTextField();
        btncari = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        btnubah1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnsimpan = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txttelp = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txtpw = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rblaki = new javax.swing.JRadioButton();
        rbperempuan = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(8, 36, 204));
        jPanel3.setRequestFocusEnabled(false);
        jPanel3.setVerifyInputWhenFocusTarget(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Punya gua\\PS TONI\\logo apetik.png")); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 10, 590, 90);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(8, 36, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("We Take Care Our Patient Health");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 100, 590, 17);

        tbladmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID ADMIN", "NAMA", "JENIS KELAMIN", "NO TLP", "EMAIL", "PASSWORD"
            }
        ));
        jScrollPane1.setViewportView(tbladmin);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(20, 270, 550, 210);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(8, 36, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DATA ADMIN");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 140, 590, 44);
        jPanel2.add(txtcari);
        txtcari.setBounds(20, 220, 150, 30);

        btncari.setBackground(new java.awt.Color(8, 36, 204));
        btncari.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btncari.setForeground(new java.awt.Color(255, 255, 255));
        btncari.setText("CARI");
        btncari.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncari.setOpaque(false);
        btncari.setSelected(true);
        btncari.setVerifyInputWhenFocusTarget(false);
        btncari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncariActionPerformed(evt);
            }
        });
        jPanel2.add(btncari);
        btncari.setBounds(180, 220, 80, 30);

        btnhapus.setBackground(new java.awt.Color(8, 36, 204));
        btnhapus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnhapus.setForeground(new java.awt.Color(255, 255, 255));
        btnhapus.setText("HAPUS");
        btnhapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnhapus.setOpaque(false);
        btnhapus.setSelected(true);
        btnhapus.setVerifyInputWhenFocusTarget(false);
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        jPanel2.add(btnhapus);
        btnhapus.setBounds(140, 530, 100, 40);

        btnubah1.setBackground(new java.awt.Color(8, 36, 204));
        btnubah1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnubah1.setForeground(new java.awt.Color(255, 255, 255));
        btnubah1.setText("UBAH");
        btnubah1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnubah1.setOpaque(false);
        btnubah1.setSelected(true);
        btnubah1.setVerifyInputWhenFocusTarget(false);
        btnubah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubah1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnubah1);
        btnubah1.setBounds(20, 530, 100, 40);

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 590, 620));

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 640, 720);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setForeground(new java.awt.Color(0, 0, 102));
        jPanel4.setRequestFocusEnabled(false);
        jPanel4.setVerifyInputWhenFocusTarget(false);
        jPanel4.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        btnsimpan.setBackground(new java.awt.Color(8, 36, 204));
        btnsimpan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnsimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnsimpan.setText("SIMPAN");
        btnsimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsimpan.setOpaque(false);
        btnsimpan.setSelected(true);
        btnsimpan.setVerifyInputWhenFocusTarget(false);
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });
        jPanel5.add(btnsimpan);
        btnsimpan.setBounds(240, 460, 190, 40);

        txtid.setEditable(false);
        txtid.setText("ID ADMIN");
        txtid.setToolTipText("");
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        jPanel5.add(txtid);
        txtid.setBounds(240, 190, 190, 30);

        txtnama.setText("NAMA");
        jPanel5.add(txtnama);
        txtnama.setBounds(240, 230, 190, 30);

        txttelp.setText("NO TELEPON");
        jPanel5.add(txttelp);
        txttelp.setBounds(240, 310, 190, 30);

        txtemail.setText("EMAIL");
        jPanel5.add(txtemail);
        txtemail.setBounds(240, 350, 190, 30);

        txtpw.setText("PASSWORD");
        jPanel5.add(txtpw);
        txtpw.setBounds(240, 390, 190, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(8, 36, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("INSERT DATA");
        jPanel5.add(jLabel4);
        jLabel4.setBounds(0, 90, 590, 30);

        buttonGroup1.add(rblaki);
        rblaki.setText("laki-laki");
        jPanel5.add(rblaki);
        rblaki.setBounds(240, 270, 80, 30);

        buttonGroup1.add(rbperempuan);
        rbperempuan.setText("perempuan");
        jPanel5.add(rbperempuan);
        rbperempuan.setBounds(340, 270, 90, 30);

        jLabel5.setText("ID");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(140, 190, 60, 30);

        jLabel6.setText("NAMA");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(140, 230, 70, 30);

        jLabel7.setText("JENIS KELAMIN");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(140, 270, 90, 30);

        jLabel8.setText("NO TELP");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(140, 310, 80, 30);

        jLabel9.setText("EMAIL");
        jPanel5.add(jLabel9);
        jLabel9.setBounds(140, 350, 80, 30);

        jLabel10.setText("PASSWORD");
        jPanel5.add(jLabel10);
        jLabel10.setBounds(140, 390, 90, 30);

        jPanel4.add(jPanel5);
        jPanel5.setBounds(0, 50, 590, 620);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(640, 0, 640, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
       String jenis = null;
        if(rblaki.isSelected()){
            jenis = "LAKI-LAKI";
        }else if(rbperempuan.isSelected()){
            jenis = "PEREMPUAN";
        }
        String sql = "INSERT INTO admin (id_admin,nama,jenis_kelamin,no_telepon,email,password) VALUES (?,?,?,?,?,?)";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, txtid.getText());
            stat.setString(2, txtnama.getText());
            stat.setString(3, jenis);
            stat.setString(4, txttelp.getText());
            stat.setString(5, txtemail.getText());
            stat.setString(6, txtpw.getText());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            kosong();
            txtid.requestFocus();
        } catch (HeadlessException | NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Data gagal disimpan"+e);
        }
        datatable();
        aktif();
        autonumber();
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void btncariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncariActionPerformed
        // TODO add your handling code here:
        datatable();
        kosong();
    }//GEN-LAST:event_btncariActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhapusActionPerformed

    private void btnubah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubah1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnubah1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncari;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JButton btnubah1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rblaki;
    private javax.swing.JRadioButton rbperempuan;
    private javax.swing.JTable tbladmin;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtpw;
    private javax.swing.JTextField txttelp;
    // End of variables declaration//GEN-END:variables
}
